server:
  port: 10111
  servlet:
    context-path: /gateway/v1

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, refresh
      base-path: /monitoring      
  endpoint:
    health:
      show-details: always
  security:
    enable: false