server:
  port: 10222
  servlet:
    context-path: /users/v1

spring:
  application:
    name: usersMS
        
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, refresh
      base-path: /monitoring      
  endpoint:
    health:
      show-details: always
  security:
    enable: false