server:
  port: 9999
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgottling/java-practice
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
          search-paths: /springMS-demo/configs
          force-pull: true
          delete-untracked-branches: true