server:
  port: 9999
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgottling/java-practice
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
          search-paths: /springMS-demo/configs
          force-pull: true
          delete-untracked-branches: true

management:
  security:
    enable: false
  endpoints:
    web:
      exposure:
        include: info, health, metrics, refresh
      base-path: /monitoring
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka